version: "3"

tasks:
  build-linux:
    cmds:
      - go build -o bin/ectary-linux-amd64 main.go
    env:
      GOOS: linux
      GOARCH: amd64
  build-windows:
    cmds:
      - go build -o bin/ectary-windows-amd64.exe main.go
    env:
      GOOS: windows
      GOARCH: amd64
  build:
    cmds:
      - task: build-linux
      - task: build-windows